sudo: required

language: ruby

services:
  - docker

env:
  - TARGET_CONTAINER_ID=factorio

before_script:
  - docker build -t factorio .
  - docker run -d --name $TARGET_CONTAINER_ID factorio

script:
  - bundle exec rspec
