sudo: required

language: ruby

services:
  - docker

env:
  - TARGET_CONTAINER_ID=factorio

before_script:
  - docker build -t facrotio .
  - docker run -d --name $TARGET_CONTAINER_ID factorio
  - docker exec -it $TARGET_CONTAINER_ID docker -v

script:
  - bundle exec rspec
